### ISSUE TITLE
99.场景分析

### ISSUE THREAD

**Issue by o1wish** [zlx362211854/daily-study#155]

**Comment by zlx362211854** [comment]
* 使用padding-bottom来占位
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
    /* 盒子层 */
    .box {
      width: 800px;
      height: 600px;
    }
    /* 占位层，通过padding-bottom帮忙占住图片的位置，（600 / 800 = 75%） */
    .box::after {
      content: '';
      height: 0;
      padding-bottom: 75%;
    }
  </style>
</head>
<body>
  <div class="box">
      <img src="https://tva1.sinaimg.cn/large/006tNbRwgy1ga3813qmnuj30m80go0uk.jpg" alt="" class="img">
  </div>
  <div>图片下面的文字图片下面的文字图片下面的文字图片下面的文字</div>
</body>
</html>
```

**Comment by goldEli** [comment]
1. 改变img为块级元素，设置宽高，这样在未加载完成时就不会塌陷。
2. div 替代 img，用 background-image 设置图片。但这样做改变了图片标签的语义会影响搜索引擎抓取。
3. 最好的体验是，在图片未加载成功，占位的同时展示占位背景。

```html
<div class="placeholder">
    <img src="myimage.jpeg" />
</div>
```
```css
.placeholder {
    width: 300;
    height: 300;
    background-repeat: no-repeat;
    background-size: contain;
    background-image: url('my_placeholder.png');
}
```
