### ISSUE TITLE
day 3. Draw a triangle with css

### ISSUE THREAD

**Issue by goldEli** [zlx362211854/daily-study#18]
###

**Comment by zlx362211854** [comment]
css三角关键在border的绘制：
先画一个width，height都为0的div,然后给他的四个边都加上一个粗实线。
```html
<div class="triangel"></div>
```
```css
    .triangel {
      width: 0;
      height: 0;

      border-top:50px solid red;
      border-right:50px solid yellow;
      border-bottom:50px solid blue;
      border-left:50px solid indigo;
    }
```
效果是这样的：
![image](https://user-images.githubusercontent.com/22437181/61919108-b34a9a00-af86-11e9-92e3-cc5c11d2b690.png)
就构成了4个不同方向的三角形。
需要哪个三角形，就把其他方向的border的颜色透明度设置为0，比如我要左边的这个三角形，就把上，下，右边透明度设置为0:
```css
    .triangel {
      width: 0;
      height: 0;

      border-top:50px solid rgba(0,0,0,0);
      border-right:50px solid rgba(0,0,0,0);
      border-bottom:50px solid rgba(0,0,0,0);
      border-left:50px solid indigo;
    }
```
效果看起来就是：
![image](https://user-images.githubusercontent.com/22437181/61919237-44217580-af87-11e9-861f-288aa4fa526b.png)

**Comment by goldEli** [comment]
**大体思路：**

1. 创建一个 `div`，宽高相等，再单独设置上下左右的 `border`

![1](https://user-images.githubusercontent.com/18217162/61919682-497fbf80-af89-11e9-8ad4-8d9ca272b66d.jpg)


2. 将 `div` 的宽高设为 0

![1564105116503](https://user-images.githubusercontent.com/18217162/61919686-4f75a080-af89-11e9-93ac-c3b0e73099b7.jpg)


3. 将上左右的 `border` 颜色设置成 `transparent`，就得到一个向上的三角形了

![1564105157614](https://user-images.githubusercontent.com/18217162/61919693-57354500-af89-11e9-9ea8-3c39a4c68418.jpg)


**最终代码如下：**

```css
    .triangle_to_top{
      width: 0; 
      height: 0; 
      border-top: 10px solid transparent;
      border-bottom: 10px solid blue;
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
    }
    .triangle_to_left{
      width: 0; 
      height: 0; 
      border-top: 10px solid transparent;
      border-bottom: 10px solid transparent;
      border-right: 10px solid red;
    }
    .triangle_to_right{
      width: 0; 
      height: 0; 
      border-top: 10px solid transparent;
      border-bottom: 10px solid transparent;
      
      border-left: 10px solid green;
    }
    .triangle_to_bottom{
      width: 0; 
      height: 0; 
      border-top: 10px solid brown;
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
    }
```
```html
    <div class="triangle_to_top"></div>
    <div class="triangle_to_right"></div>
    <div class="triangle_to_bottom"></div>
    <div class="triangle_to_left"></div>
```

**Reference:**
[CSS Triangle](https://css-tricks.com/snippets/css/css-triangle/)
